---
title: "Fitting a mixture model"
author: "Inge Wortel"
date: "16/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Package

```{r pack}
library( mclust )
```

## Tests

#### Two normal distributions

We first generate data from normal distributions:

```{r}

realMu1 <- 1
realMu2 <- 2
realSigma1 <- 2
realSigma2 <- 0.5
n <- 1000
frac1 <- 0.5

n1 <- round(frac1*n)
n2 <- n - n1

data1 <- rnorm( n1, realMu1, realSigma1 )
data2 <- rnorm( n2, realMu2, realSigma2 )
data <- c( data1, data2 )

```

Now try to fit it.

```{r}

estimateComponents <- function( data ){
  
  fit <- Mclust( data )
  parms <- fit$parameters
  
  out <- data.frame( 
    prop = parms$pro,
    mu = parms$mean,
    sd = sqrt( parms$variance$sigmasq)
  )

  out
  
}

deltaAIC <- function( data, kref, k ){
  
  fit1 <- Mclust( data, G = kref )
  fit2 <- Mclust( data, G = k )
  
  AIC1 <- AIC( fit1 )
  AIC2 <- AIC( fit2 )
  
  dAIC <- AIC2 - AIC1
  dAIC
  
}

# dAIC of 1 Gaussian (reference) versus 2 Gaussian fit:
deltaAIC( data, 1, 2 )

```


## On the tracks

```{r}
load( "tracks1D.Rdata" )

parms <- names( all.tracks )


dxData <- lapply( all.tracks, function(x) {
  
  t( sapply( subtracks( x, 1 ), displacementVector ) )[,1] 
  
})

parms <- as.data.frame( t( sapply( names(dxData), function(x) unlist( strsplit( x, "-"))) ) )
colnames(parms) <- c("mact","lact")

nComp <- sapply( seq(1,length(dxData)), function(x){
  estimateComponents( dxData[[x]] )
} )
nComp2 <- sapply( nComp, length )
nComp3 <- nComp2[ seq(1,length(nComp2))%%3 == 0]

dAIC <- sapply( seq(1,length(dxData)), function(x){
  deltaAIC( dxData[[x]], 1, 3 )
} )

output <- parms
output$nC <- nComp3
output$dAIC <- dAIC



```




